import { ToolMeta } from "@/types";

export const TOOLS: ToolMeta[] = [
  {
    id: "scan-to-pdf",
    category: "convert",
    nameKey: "tools.convert.scanToPdf.title",
    descriptionKey: "tools.convert.scanToPdf.description",
    href: "/tools/scan-to-pdf",
    icon: "scan",
    outputType: "application/pdf",
  },
  {
    id: "merge-pdf",
    category: "organize",
    nameKey: "tools.organize.mergePdf.title",
    descriptionKey: "tools.organize.mergePdf.description",
    href: "/tools/merge-pdf",
    icon: "merge",
    multipleFiles: true,
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "split-pdf",
    category: "organize",
    nameKey: "tools.organize.splitPdf.title",
    descriptionKey: "tools.organize.splitPdf.description",
    href: "/tools/split-pdf",
    icon: "split",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "rotate-pdf",
    category: "organize",
    nameKey: "tools.organize.rotatePdf.title",
    descriptionKey: "tools.organize.rotatePdf.description",
    href: "/tools/rotate-pdf",
    icon: "rotate",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "reorder-pages",
    category: "organize",
    nameKey: "tools.organize.reorderPages.title",
    descriptionKey: "tools.organize.reorderPages.description",
    href: "/tools/reorder-pages",
    icon: "reorder",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "delete-pages",
    category: "organize",
    nameKey: "tools.organize.deletePages.title",
    descriptionKey: "tools.organize.deletePages.description",
    href: "/tools/delete-pages",
    icon: "delete",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "extract-pages",
    category: "organize",
    nameKey: "tools.organize.extractPages.title",
    descriptionKey: "tools.organize.extractPages.description",
    href: "/tools/extract-pages",
    icon: "extract",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "compress-pdf",
    category: "optimize",
    nameKey: "tools.optimize.compressPdf.title",
    descriptionKey: "tools.optimize.compressPdf.description",
    href: "/tools/compress-pdf",
    icon: "compress",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "jpg-to-pdf",
    category: "convert",
    nameKey: "tools.convert.jpgToPdf.title",
    descriptionKey: "tools.convert.jpgToPdf.description",
    href: "/tools/jpg-to-pdf",
    icon: "imageToPdf",
    multipleFiles: true,
    acceptsInput: ["image"],
    outputType: "application/pdf",
  },
  {
    id: "pdf-to-jpg",
    category: "convert",
    nameKey: "tools.convert.pdfToJpg.title",
    descriptionKey: "tools.convert.pdfToJpg.description",
    href: "/tools/pdf-to-jpg",
    icon: "pdfToImage",
    acceptsInput: ["pdf"],
    outputType: "image/jpeg",
  },
  {
    id: "pdf-to-png",
    category: "convert",
    nameKey: "tools.convert.pdfToPng.title",
    descriptionKey: "tools.convert.pdfToPng.description",
    href: "/tools/pdf-to-png",
    icon: "pdfToImage",
    acceptsInput: ["pdf"],
    outputType: "image/png",
  },
  {
    id: "pdf-to-text",
    category: "convert",
    nameKey: "tools.convert.pdfToText.title",
    descriptionKey: "tools.convert.pdfToText.description",
    href: "/tools/pdf-to-text",
    icon: "pdfToText",
    acceptsInput: ["pdf"],
    outputType: "text/plain",
  },
  {
    id: "pdf-to-word",
    category: "convert",
    nameKey: "tools.convert.pdfToWord.title",
    descriptionKey: "tools.convert.pdfToWord.description",
    href: "/tools/pdf-to-word",
    icon: "pdfToWord",
    acceptsInput: ["pdf"],
    requiresProvider: true,
  },
  {
    id: "word-to-pdf",
    category: "convert",
    nameKey: "tools.convert.wordToPdf.title",
    descriptionKey: "tools.convert.wordToPdf.description",
    href: "/tools/word-to-pdf",
    icon: "wordToPdf",
    acceptsInput: ["word"],
    requiresProvider: true,
  },
  {
    id: "pdf-to-excel",
    category: "convert",
    nameKey: "tools.convert.pdfToExcel.title",
    descriptionKey: "tools.convert.pdfToExcel.description",
    href: "/tools/pdf-to-excel",
    icon: "pdfToExcel",
    acceptsInput: ["pdf"],
    requiresProvider: true,
  },
  {
    id: "excel-to-pdf",
    category: "convert",
    nameKey: "tools.convert.excelToPdf.title",
    descriptionKey: "tools.convert.excelToPdf.description",
    href: "/tools/excel-to-pdf",
    icon: "excelToPdf",
    acceptsInput: ["excel"],
    requiresProvider: true,
  },
  {
    id: "edit-pdf",
    category: "edit",
    nameKey: "tools.edit.editPdf.title",
    descriptionKey: "tools.edit.editPdf.description",
    href: "/tools/edit-pdf",
    icon: "edit",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "watermark",
    category: "edit",
    nameKey: "tools.edit.watermark.title",
    descriptionKey: "tools.edit.watermark.description",
    href: "/tools/watermark",
    icon: "watermark",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "page-numbers",
    category: "edit",
    nameKey: "tools.edit.pageNumbers.title",
    descriptionKey: "tools.edit.pageNumbers.description",
    href: "/tools/page-numbers",
    icon: "pageNumbers",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "crop-pdf",
    category: "edit",
    nameKey: "tools.edit.cropPdf.title",
    descriptionKey: "tools.edit.cropPdf.description",
    href: "/tools/crop-pdf",
    icon: "crop",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "annotate-pdf",
    category: "edit",
    nameKey: "tools.edit.annotatePdf.title",
    descriptionKey: "tools.edit.annotatePdf.description",
    href: "/tools/annotate-pdf",
    icon: "annotate",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "protect-pdf",
    category: "security",
    nameKey: "tools.security.protectPdf.title",
    descriptionKey: "tools.security.protectPdf.description",
    href: "/tools/protect-pdf",
    icon: "lock",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "unlock-pdf",
    category: "security",
    nameKey: "tools.security.unlockPdf.title",
    descriptionKey: "tools.security.unlockPdf.description",
    href: "/tools/unlock-pdf",
    icon: "unlock",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
  {
    id: "remove-metadata",
    category: "security",
    nameKey: "tools.security.removeMetadata.title",
    descriptionKey: "tools.security.removeMetadata.description",
    href: "/tools/remove-metadata",
    icon: "metadata",
    acceptsInput: ["pdf"],
    outputType: "application/pdf",
  },
];

export const TOOL_CATEGORIES = [
  { id: "organize", nameKey: "tools.organize.title", icon: "organize" },
  { id: "optimize", nameKey: "tools.optimize.title", icon: "optimize" },
  { id: "convert", nameKey: "tools.convert.title", icon: "convert" },
  { id: "edit", nameKey: "tools.edit.title", icon: "edit" },
  { id: "security", nameKey: "tools.security.title", icon: "security" },
] as const;

export function getToolsByCategory(category: string): ToolMeta[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getToolById(id: string): ToolMeta | undefined {
  return TOOLS.find((t) => t.id === id);
}
